import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import MoneyConverter from "@/components/MoneyConverter";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Data Conversion App - NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <section className="w-full grid md:grid-cols-2">
            <MoneyConverter />
            <div className={styles.conversionBox}>
              <h2>Validador de Cédulas</h2>
              <div></div>
            </div>
          </section>
        </div>
      </main>
    </>
  );
}
